### ISSUE TITLE
sed: can't read calcvor_onelev.in: No such file or directory

### ISSUE THREAD

**Issue by Ai33L** [zappag/pyTRACK-CMIP6#1]
Hi Giuseppe,

I get this error when I try to run your code. 

sed: can't read calcvor_onelev.in: No such file or directory

I suspect this is because track_wrapper/trackdir has a file called calcvor.in that you've renamed in your version, but have missed out on committing.

Cheers,
Abel

**Comment by zappag** [comment]
Thanks Abel. I have pushed a fix. Remember to rerun python setup_track.py first ...

There might be others to fix similar to this one. Please let me know how it goes. 

Cheers,

Giuseppe
